### ISSUE TITLE
Explantion of midi type

### ISSUE THREAD

**Issue by RKelln** [attwad/python-osc#116]
I'm looking to send midi through OSC, but a bit confused about the 4 tuple midi as described:
https://github.com/attwad/python-osc/blob/7f00183f7b5119696660fd488ee0cc33edecc0b7/pythonosc/parsing/osc_types.py#L380

"A valid MIDI message: (port id, status byte, data1, data2)"

Midi typically comes as a 3 byte message: status byte, byte 2, byte 3:
https://en.wikipedia.org/wiki/MIDI#Technical_specifications

So I'm wondering with the "port id" byte is and why it is required for sending midi? Thanks!

**Comment by attwad** [comment]
The comments for data types were mostly copied verbatim from the OSC spec http://opensoundcontrol.org/spec-1_0.
I've used OSC to get rid of MIDI personally so I haven't had to use this message type, I am unsure what the port_id means, even though the spec says that we need a status, byte 2 and byte 3, we need to address it to a particular midi device no? I think that could be an explanation for the port id.

**Comment by RKelln** [comment]
OK, thanks for the quick reply, I suppose that must be the midi port, which seems redundant to me since I'm using OSC. :)

**Comment by arashmath** [comment]
Dear @RKelln and @attwad,
I would really appreciate it if you could help me with my problem which is relevant to part of this issue:
I'm trying to send a MIDI file using OSC (to MAX MSP), but I'm stuck in the way I should read the MIDI file from my local machine: Currently I'm trying to read it as bytes and then seding it as in:
```
client = SimpleUDPClient(ip, port)
myfile = open("melody1.mid", "rb")
byte = myfile.read()
client.send_message("/", byte)
```

 which is not working, since I'm getting this error in MAX MSP:
`udpreceive: OSC Unrecognized type tag b. Unable to process message.
`

Since I can see you are able to send MIDI files over OSC, could you please kindly help me regarding this?
In case you need more details, I have previously asked this question on [Reddit](https://www.reddit.com/r/MaxMSP/comments/s5c5d3/comment/ijdlzrd/?utm_source=share&utm_medium=web2x&context=3) and [Stack Overflow](https://stackoverflow.com/questions/73260192/sending-midi-file-using-python-to-max-msp-or-ableton), but didn't get any replies.
Thanks in advance.

**Comment by RKelln** [comment]
I had midi messages that were sent over OSC, rather than midi files. Your midi file reading looks too simple in that code example, you probably want to find project that can read your midi file then loop through the midi messages and send them through OSC. You'll probably have to deal with the timing of the message playback as well?

Also take a look at the `[OSCOutput` function](https://github.com/RKelln/onsets-and-frames/blob/928ab6ea672112678da7117af4bc013bf75c07dd/realtime_transcribe.py#L144) I wrote for inspiration. 

Using something like [mido](https://mido.readthedocs.io/en/latest/) you might do:

```python
client = SimpleUDPClient(ip, port)
mid = mido.MidiFile('song.mid')
for msg in mid.play():
    bytes = msg.bytes()
    bytes.insert(0, midi_port)
    client.send_message("/", tuple(bytes))
```
