### ISSUE TITLE
Problematic type guessing in add_arg cause multiple issues

### ISSUE THREAD

**Issue by Nagasaki45** [attwad/python-osc#36]
python-osc version: 1.6.1
python version: 3.5.2
numpy version: 1.11.2

I'm trying to call `add_arg` with an argument of type `numpy.float64`.

# Issue 1

The call succeeds but keeps an incorrect data in the builder `args` property.

```python
In [1]: import numpy as np

In [2]: from pythonosc.osc_message_builder import OscMessageBuilder

In [3]: builder = OscMessageBuilder(address='/whatever')

In [4]: builder.add_arg(np.float64(1.23))

In [5]: builder.args
Out[5]: [(None, 1.23)]
```

Calling `builder.build()` fails with unclear error.

```python
In [6]: builder.build()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-28171a806b58> in <module>()
----> 1 builder.build()

/home/nagasaki45/code/CruftFest/wheel_speed_analyser/env/lib/python3.5/site-packages/pythonosc/osc_message_builder.py in build(self)
    102 
    103       # Write the parameters.
--> 104       arg_types = "".join([arg[0] for arg in self._args])
    105       dgram += osc_types.write_string(',' + arg_types)
    106       for arg_type, value in self._args:

TypeError: sequence item 0: expected str instance, NoneType found
```

Solving this in `add_arg` itself will be better of course. I'm not sure if aditional validation in `build` make sense here because there is no explicit way to add arguments except from `add_arg`.

# Issue 2

In my opinion, there is really no reason for restricting the usage of types that "looks like" floats, e.g. `np.float64`. Moreover, notice that

```python
In [7]: isinstance(np.float64(1.23), float)
Out[7]: True
```

Would you consider changing the type guessing to use `isinstance` instead of equality check altogether? I can't see a reason not to...

Thanks!

**Comment by rec** [comment]
Regarding Issue 2: even using `isinstance` is un-Pythonic.  

The Python way is to go ahead as if the variable "looks like" a float, and allow the code to throw an exception if it doesn't.  If you feel those exceptions aren't clear, then that can be fixed by catching and then rethrowing a better exception.

**Comment by Nagasaki45** [comment]
Hi @rec, thanks for commenting!

Note that the purpose of the type guessing is to match the correct OSC data type for the argument, not for deciding what to do with the argument (computational wise). BTW, the type guessing already exist, but use explicit equality check (`type(arg) == float`).

**Comment by attwad** [comment]
Right, I agree that using isinstance here might be a better choice as the library here is just passing that argument down to struct.pack(...) calls which will throw an exception if the argument cannot be packed (which is caught and wrapped), it doesn't really qualify as heavy business logic to me so I'm fine to just use isinstance here.

For numpy I tested and packing a float64 gives the same result as a builtin float because it _behaves_ like a float I suppose:
In [42]: a = np.float64(42)

In [43]: struct.pack(">f", a)
Out[43]: b'B(\x00\x00'

In [44]: struct.pack(">f", 42.)
Out[44]: b'B(\x00\x00'
