### ISSUE TITLE
s/custom UDP server and client/new asyncio module in python 3.4

### ISSUE THREAD

**Issue by attwad** [attwad/python-osc#5]
Will tackle that this week once I familiarized myself with the new paradigm/syntax of coroutines in Python. Sounds like fun.

**Comment by jsheedy** [comment]
I didn't even realize this was an open issue, I hope I didn't steal your thunder :).   I implemented it because I'm using another module along with python-osc which only supported asyncio. So I wanted to get everything running on the asyncio loop rather than a combination of threads and asyncio.  It's working great so far!  

Thanks again for the package, it works great and the code is nice and clean to work in. :clap:

**Comment by attwad** [comment]
That's just an old issue I filed to not forget about it, but I did... haha
thanks for doing it
