### ISSUE TITLE
Typify code

### ISSUE THREAD

**Issue by attwad** [attwad/python-osc#86]
This means we drop 3.4 support because types are only for 3.5 unless we add an external dependency (backport of types) which I'd prefer to avoid.

**Comment by attwad** [comment]
I have no time to produce code myself now but happy to do the reviews, thanks

**Comment by attwad** [comment]
Fixed by #87

**Comment by DrLuke** [comment]
The PR didn't yet typify the code, I'm still working on that! :)

**Comment by attwad** [comment]
oh you're right, I was too hasty...

**Comment by DrLuke** [comment]
Typing is being worked in in #88

**Comment by DrLuke** [comment]
So turns out variable annotation was only added in 3.6: https://docs.python.org/3.6/whatsnew/3.6.html

Should this be omitted in favor of 3.5 support? I personally would prefer to use the newer features to be more future proof. On the other hand variable annotation isn't really that important, so does it warrant potentially excluding a portion of the userbase?

**Comment by attwad** [comment]
I don't really think variable annotations gives much improvement, I'd better stay with 3.5 support.

**Comment by DrLuke** [comment]
In `osc_packet.py` there's some type confusion in `OscPacket`'s `__init__`:

https://github.com/attwad/python-osc/blob/6926741be689b3b8492993b231957c46c5c4207e/pythonosc/osc_packet.py#L60-L65

Depending on whether the dgram is a bundle or message `self._messages` is a list or a tuple. Is this intended, or could both be returned as a list?

**Comment by attwad** [comment]
Ah good catch, both should be lists ([]) indeed

**Comment by DrLuke** [comment]
Little inconvenience: Multiple methods of `OscBundle` in https://github.com/attwad/python-osc/blob/6926741be689b3b8492993b231957c46c5c4207e/pythonosc/osc_bundle.py return `OscBundle`s, which is something that can't be resolved until python 3.7. Thus I had to set the return type to `Any` everywhere this is the case.
From Python 3.7 and upwards you can `from __future__ import annotations`, which is a greatly improved version of type annotations which stores the type annotations as strings instead of evaluating them at parse time. See [PEP 563](https://www.python.org/dev/peps/pep-0563/) for more information.

**Comment by DrLuke** [comment]
This issue can be closed now.

**Comment by attwad** [comment]
Fixed by  #88
